### ISSUE TITLE
Windows Install Error

### ISSUE THREAD

**Issue by yonderbread** [naturecodevoid/ct-js-installer#1]
Running the installer causes a small error dialog to appear saying "Failed to execute main script."

(Windows 10)

**Comment by naturecodevoid** [comment]
I believe I know what the problem is, but if you want to you could run the .exe file in a command prompt to get the full error and post it here.

**Comment by yonderbread** [comment]
Will do

**Comment by yonderbread** [comment]
Oh, it seems the new release fixed the problem. Ty
